var json = {
	"bandInfo1": {
		"fname": ["fname:", "Jon"],
		"bname": ["Band Name:", "Slayer"],
		"group": ["Genre:", "rock"],
		"email": ["Email:", "your@email.com"],
		"startdate": ["Date requesting:", "2012-12-10"],
		"instrument1": ["instrument1:", "yes"],
		"instrument2": ["instrument2:", "no"],
		"instrument3": ["instrument3:", "no"],
		"instrument4": ["instrument4:", "no"],
		"instrument5": ["instrument5:", "no"],
		"instrument6": ["instrument6:", "no"],
		"instrument7": ["instrument7:", "no"],
		"instrument8": ["instrument8:", "no"],
		"instrument9": ["instrument9:", "no"],
		"other1": ["Other info:", "None"],
		"tickets": ["Amount of tickets needed:","10"]
	},
	"bandInfo2": {
		"fname": ["fname:", "Steve"],
		"bname": ["Band Name:", "Metallica"],
		"group": ["Genre:", "metal"],
		"email": ["Email:", "your@email.com"],
		"startdate": ["Date requesting:", "2012-03-09"],
		"instrument1": ["instrument1:", "yes"],
		"instrument2": ["instrument2:", "no"],
		"instrument3": ["instrument3:", "no"],
		"instrument4": ["instrument4:", "no"],
		"instrument5": ["instrument5:", "no"],
		"instrument6": ["instrument6:", "no"],
		"instrument7": ["instrument7:", "no"],
		"instrument8": ["instrument8:", "no"],
		"instrument9": ["instrument9:", "no"],
		"other1": ["Other info:", "None"],
		"tickets": ["Amount of tickets needed:","1"]
	},
	"bandInfo3": {
		"fname": ["fname:", "Cory"],
		"bname": ["Band Name:", "Dream Theater"],
		"group": ["Genre:", "rock"],
		"email": ["Email:", "your@email.com"],
		"startdate": ["Date requesting:", "2012-03-09"],
		"instrument1": ["instrument1:", "yes"],
		"instrument2": ["instrument2:", "no"],
		"instrument3": ["instrument3:", "no"],
		"instrument4": ["instrument4:", "no"],
		"instrument5": ["instrument5:", "no"],
		"instrument6": ["instrument6:", "no"],
		"instrument7": ["instrument7:", "no"],
		"instrument8": ["instrument8:", "no"],
		"instrument9": ["instrument9:", "no"],
		"other1": ["Other info:", "None"],
		"tickets": ["Amount of tickets needed:","1"]
	}
}
